import {
  DashboardOutlined,
  UserOutlined,
  PicCenterOutlined,
  BuildOutlined,
  MobileOutlined,
  // MoneyCollectOutlined,
  // MoneyCollectFilled,
  MessageOutlined,
  PicRightOutlined,
  SettingOutlined,
  FileImageOutlined,
  LogoutOutlined,
  SwitcherOutlined,
  BellOutlined,
} from '@ant-design/icons';

export const SidebarData = [
  {
    key: 'dashboard',
    title: 'Dashboard',
    icon: DashboardOutlined,
    link: '/',
  },
  {
    key: 'labourers',
    title: 'Labourers',
    icon: UserOutlined,
    link: '/labourer',
    isPermissionBased: true,
  },
  {
    key: 'agents',
    title: 'Agents',
    icon: PicCenterOutlined,
    link: '/agent',
    isPermissionBased: true,
  },
  {
    key: 'agents',
    title: `Agents' Labourers`,
    icon: UserOutlined,
    link: '/agent-labourer',
    isPermissionBased: true,
  },
  {
    key: 'factoryOwners',
    title: 'Factories',
    icon: BuildOutlined,
    link: '/factory',
    isPermissionBased: true,
  },
  {
    key: 'appData',
    title: 'App Data',
    icon: MobileOutlined,
    link: '/app-data',
  },
  {
    key: 'MapData',
    title: 'Mapped Data',
    icon: MobileOutlined,
    link: '/mapped-users',
  },
  {
    key: 'jobPosts',
    title: 'Jobs',
    icon: SwitcherOutlined,
    link: '/job',
    isPermissionBased: true,
  },
  {
    key: 'jobApplications',
    title: 'Job Approvals',
    icon: PicRightOutlined,
    link: '/approval',
    isPermissionBased: true,
  },
  // {
  //   key: 'salaries',
  //   title: 'Salaries',
  //   icon: MoneyCollectOutlined,
  //   link: '/salary',
  // },
  // {
  //   key: 'commissions',
  //   title: 'Commissions',
  //   icon: MoneyCollectFilled,
  //   link: '/commission',
  // },
  {
    key: 'industryTypes',
    title: 'Industry Types',
    icon: SwitcherOutlined,
    link: '/milltype',
  },
  {
    key: 'notification',
    title: 'Notifications',
    icon: BellOutlined,
    link: '/notification',
    isPermissionBased: true,
  },
  {
    key: 'flyers',
    title: 'Flyers',
    icon: FileImageOutlined,
    link: '/flyers',
  },
  {
    key: 'support',
    title: 'Support',
    icon: MessageOutlined,
    link: '/support',
  },
  {
    key: 'adminAccess',
    title: 'Admins',
    icon: SettingOutlined,
    link: '/admin',
    isPermissionBased: true,
  },

  {
    key: 'logout',
    title: 'Logout',
    icon: LogoutOutlined,
    link: '/logout',
  },
];
